<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUSs80W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUSs80W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQUSs80W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQUSs80W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQUSs80W\App_KernelDevDebugContainer([
    'container.build_hash' => 'QUSs80W',
    'container.build_id' => 'c7b18c00',
    'container.build_time' => 1717694691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUSs80W');
