<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKQIw9X6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKQIw9X6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKQIw9X6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKQIw9X6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKQIw9X6\App_KernelDevDebugContainer([
    'container.build_hash' => 'KQIw9X6',
    'container.build_id' => '77c3b64b',
    'container.build_time' => 1718890398,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKQIw9X6');
