<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBuxCS7s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBuxCS7s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBuxCS7s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBuxCS7s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBuxCS7s\App_KernelDevDebugContainer([
    'container.build_hash' => 'BuxCS7s',
    'container.build_id' => '50b48ebe',
    'container.build_time' => 1718027767,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBuxCS7s');
